name: OursLists
options:
  bundleIdPrefix: com.short
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  FirebaseAuth:
    url: https://github.com/firebase/firebase-ios-sdk
    version: "11.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    version: "8.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "5824UP464U"

targets:
  OursLists:
    type: application
    platform: iOS
    sources:
      - path: OursLists
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.short.OursLists
        INFOPLIST_FILE: OursLists/Info.plist
        CODE_SIGN_ENTITLEMENTS: OursLists/OursLists.entitlements
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: "YES"
    dependencies:
      - package: FirebaseAuth
        product: FirebaseAuth
      - package: FirebaseAuth
        product: FirebaseFirestore
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
    entitlements:
      path: OursLists/OursLists.entitlements
      properties:
        aps-environment: development
